### ISSUE TITLE
Nie można dodać podstrony

### ISSUE THREAD

**Issue by michu2k** [sruupl/batflat#1]
Strona nie zapisuje się, wyskakuje komunikat: 
 [@getNew] Żądany zasób nie istnieje.

**Comment by sruupl** [comment]
Czy ten błąd występuje za każdym razem kiedy dodajesz stronę?

**Comment by michu2k** [comment]
Teraz zauważyłem, że za każdym razem gdy stworzymy stronę a nie wpiszemy zawartości. W poprzedniej wersji błąd ten nie występował. Można było pozostawić pole z treścią puste.

**Comment by sruupl** [comment]
Fixed in 1.3.1
