### ISSUE TITLE
Help with GetUserInfo('access') 

### ISSUE THREAD

**Issue by Dejmienwp** [sruupl/batflat#103]
Mam kod w admin.php
```
 private function _importevents()
 {    
        $rows = $this->db('events')->where('status', 'activ')->asc('datestart')->toArray(); 
        $result = [];        

        foreach ($rows as $row) {
            $row['dates'] = date('d.m.Y H:i', strtotime($row['datestart']));
            $row['role'] = $this->core->getUserInfo('role');    
            $row['access'] = $this->core->getUserInfo('access');  
            if ($this->core->getUserInfo('access') != 'all') {
                $a1 = array("wydarzenia", "all"); 
                $resulte = array_intersect($a1, explode(',', $this->core->getUserInfo('access')));
                foreach ($resulte as $rowe) {
                $rowe = $rowe . ' ';
            }  
            $row['access'] = $rowe;   
        }
            $result[] = $row;
        }  
        return $result; 
 }
```
oraz 

`{if: $value.access == 'wydarzenia' || $value.access == 'all' } ` w index.html

Tak jak z "all" działa, tak z 'wydarzenia' już nie idzie. 
Chcę zrobić, żeby dostęp do edycji mieli tylko Ci co mają dostęp do tego modułu.
Nie umiem wyciągnąć z "access" pojedynczego dostepu.

Może ktoś kto zna bardziej php i batflata ma pomysł :(

**Comment by klocus** [comment]
Sprawdź proszę, czy `$value.access` na pewno zwraca "wydarzenia" lub jakąkolwiek inną wartość. 

Włącz również DEV_MODE w zmiennych środowiskowych Batflata i dumpuj/printuj sobie zawartość zmiennych, np. `$resulte`. Daj znać.

**Comment by Dejmienwp** [comment]
Hej. Dzięki za odpowiedź. 
`               if ($this->core->getUserInfo('access') != 'all') {
                   $a1 = array("wydarzenia", "dashboard"); 
                   $resulte = array_intersect($a1, explode(',', $this->core->getUserInfo('access')));
                   foreach ($resulte as $rowe) {
                   $rowe = $rowe . ' ';
               }  
               $row['access'] = $rowe; 
               print_r($resulte);  
           }`
$Value.access zwraca zawsze dashboard. Nawet gdy użytkownik na 1 pozycji ma dodane "wydarzenia"
print_r zwraca `Array ( [0] => wydarzenia [1] => dashboard )`

W DEV_MODE wywala oczywiście błąd, gdy w $a1 ustawie tylko "wydarzenia", a użytkownik nie posiada tego w "access"

Nawet Gdy $value.access - pokaże mi "wydarzenia" to if: nie przepuszcza dalej.

**Comment by klocus** [comment]
Wydaje mi się, że linijka `$resulte = array_intersect($a1, explode(',', $this->core->getUserInfo('access')));` jest zupełnie niepotrzebna. Prościej będzie sprawdzać czy w stringu znajduje się tekst "wydarzenie". Dlatego proponuję usunąć wszelkie operacje na `access` użytkownika i sprawdzać go prostym warunkiem: 

```
if (strpos($this->core->getUserInfo('access'), 'wydarzenia') !== false)
```

Adekwatnie w szablonie HTML :)

**Comment by Dejmienwp** [comment]
```
               if ($this->core->getUserInfo('access') != 'all') {
                $row['access'] = strpos($this->core->getUserInfo('access'), 'wydarzenia') !== false;
               }  
```
Zamieniłem na takie coś i działa. $Value.access = 1; 
Alę akurat to mi nie przeszkadza, bo zostanie usunięty. 
Natomiast Funkcja IF działa pięknie i bez wywalania czegokolwiek.
Widocznie za bardzo chciałem pod górke nie znając takiej funkcji 🗡️ 

Dopiero się uczę php i to na batflacie :D

**Dziękuje Ci bardzo za pomoc :)**
