### ISSUE TITLE
No fallback in Gallery for thumbnail if $width < 150 px

### ISSUE THREAD

**Issue by ghost** [sruupl/batflat#11]
If image uploaded to Gallery will have smaller width than 150 px - there is no fallback, so there will be no thumbnail and thus no image preview in Admin.

This will also generate:
`Notice: Undefined index: xs in C:\xampp\htdocs\batflat\inc\modules\galleries\Admin.php on line 133`

Basic workaround (it will treat image itself as thumbnail):
```
 else
 {
	$src[$key] = str_replace(BASE_DIR.'/', null, $imgPath);
 }
```

**Comment by michu2k** [comment]
Fixed
