### ISSUE TITLE
How to duplicate blog module

### ISSUE THREAD

**Issue by Na6eu** [sruupl/batflat#119]
Forgive my English, I'm using a translator ...
I need help. I would like to have a blog and portfolio on my website. I want to copy the "blog" module and create a portfolio on this basis. Can anyone help me? Separate "blog" rename and add it as a new module.

**Comment by joywebpro** [comment]
Comment avez-vous fais?

**Comment by karix094** [comment]
Problem rozwiązany? 
Również jestem zainteresowany
