### ISSUE TITLE
Routing?

### ISSUE THREAD

**Issue by dahliadahlia** [sruupl/batflat#13]
Hello Batflat team!

How do I customize the routing / permalinks for Batflat?

Right now is:
http://site.com/blog/post/lets-put-a-smile-on-that-face

I want to do:
http://site.com/lets-put-a-smile-on-that-face

I saw mention of routing in the documentation but I'm not sure how to use that. Thanks in advance!

**Comment by klocus** [comment]
Hi,

You can do this at "inc/modules/blog/Site.php" in public method "routes()".

**Comment by dahliadahlia** [comment]
Thank you klocus! I'll give this a try and report back.
