### ISSUE TITLE
Menu dropdown + funkcjonalność DEV_MODE

### ISSUE THREAD

**Issue by szymonwylegala** [sruupl/batflat#17]
Jak można naprawić problem z elementem menu rozwijanego ponieważ kiedy dodam nowy element i przypisując go do rodzica sam rodzic przestaje działać (nie przenosi do danej strony).

Czy w przyszłości będzie możliwość włączając tryb deweloperski tworzyć szablon do panelu administracyjnego np. w xampp? W chwili obecnej nie ma możliwość wykonania takiego szablonu - jedyną opcją jest zapewne wykupienie licencji i praca na danej domenie co może być uciążliwe...

Łączę pozdrowienia :)

**Comment by sruupl** [comment]
Przesyłam wersję widoku nawigacji jednego z użytkowników:
```html
{loop: $navigation.list}
    {if: !isset($value.children)}
    <li class="{if: $value.active || $value.class}{?= trim($value.active.' '.$value.class) ?}{/if}">
        <a href="{$value.url}" >{$value.name}</a>
    </li>
    {else}
    <li class="dropdown{if: $value.active || $value.class}{?= trim($value.active.' '.$value.class) ?}{/if} btn-group">
        <a href="{$value.url}" class="btn" style="text-transform: none;">
                                          {$value.name}
                          </a>
            <a href="{$value.url}" class="btn dropdown-toggle dropdown-toggle-split" data-target="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                                          <span class="caret"></span>
                                          </a>
        <ul class="dropdown-menu">
            {loop: $value.children}
            <li {if: $value.active || $value.class}class="{?= trim($value.active.' '.$value.class) ?}"{/if}><a href="{$value.url}">{$value.name}</a></li>
            {/loop}
        </ul>
    </li>
    {/if}
{/loop}
```

Wystarczy w katalogu motywu utworzyć katalog „modules/navigation" i tam wgrać plik nav.html. Batflat wykryje, że motyw nadpisuje oryginalny plik widoku. Zapobiega to nadpisaniu zmodyfikowanego widoku po aktualizacji.

Nie rozumiem za bardzo drugiego pytania. Otóż można wykonać szablon na serwerze lokalnym.

**Comment by cloudenv** [comment]
@szymonwylegala czemu praca na domenie miałaby być uciążliwa?
