### ISSUE TITLE
Bootstrap 4 Navigation

### ISSUE THREAD

**Issue by komputronika** [sruupl/batflat#24]
I think there is should be an option on the settings page to use Bootstrap 3 or 4. Because the HTML structure of the navigation is slightly different. Thanks.

**Comment by klocus** [comment]
Hello,

You can easily customize HTML view of navigation. Just create in your theme catalog a new dir: modules/navigation/ and paste there this file: https://github.com/sruupl/batflat/blob/master/inc/modules/navigation/view/nav.html

Batflat will detect that your theme uses a different view for a given module.
