### ISSUE TITLE
Custom batflat modules

### ISSUE THREAD

**Issue by piotr-placzek** [sruupl/batflat#29]
There are some custom modules for batflat at my GitHub.
[Syntax highlighter](https://github.com/piotr-placzek/BatFlat-SyntaxHighlighter)
[FilesToDownload](https://github.com/piotr-placzek/BatFlat-FilesToDownload)
[EmbededVideoPlayer](https://github.com/piotr-placzek/BatFlat-EmbededVideoPlayer)
----
_When I write another module, I intend to add information in this issue.
I will be grateful if you complete the links to the modules in the [ReadMe.md](https://github.com/sruupl/batflat/blob/master/ReadMe.md#modules) file._

_All modules are marked with [batflat](https://github.com/topics/batflat) and [batflat-modules](https://github.com/topics/batflat-module)._

**Comment by klocus** [comment]
I updated ReadMe.md
