### ISSUE TITLE
Labels not visible after creating new language file

### ISSUE THREAD

**Issue by Torsten-K** [sruupl/batflat#3]
Hello,

I like the simplicity of this CMS, but I have run into one issue: I created a new language file (German) from the backend and then switched the backend to this new language. But nearly all of the labels were gone, like those in the left navigation bar and also below the tiles on the dashboard. It seems like in the Englisch language file, many expressions are missing, which could be translated.

Kind regards,
Torsten

**Comment by klocus** [comment]
It seems to me that I don't understand you exactly. Have you supplemented language variables for German?

**Comment by Torsten-K** [comment]
@klocus Aaaah, stupid me, I overlooked the dropdown menu … ![dropdown menu](http://torsten.bplaced.net/batflat/settings-translation-dropdown.png) …
