### ISSUE TITLE
Sitemap plugin - Error

### ISSUE THREAD

**Issue by KonstantinFromRussia** [sruupl/batflat#37]
I activate the sitemap module.
I go to the site address - mysite/sitemap.xml
and get an error 500
![sitemap-error](https://user-images.githubusercontent.com/31459888/46907024-96b80680-cf0c-11e8-98fe-b1983e8eae66.jpg)

**Comment by klocus** [comment]
Can you activate DEV_MODE in `inc/core/defines.php?`. Please check for some errors.

**Comment by sim2github** [comment]
```
This page contains the following errors:
error on line 2 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.
```

**Comment by KonstantinFromRussia** [comment]
My Lords !!!
I am taking a **clean** distribution system from a github.
I unpack it on the server. I start, I go to the admin area, turn on the sitemap plugin.
**I do not make any additional entries.**
Then I look at adress:
http://u14445mo3.ha002.t.justns.ru/sitemap.xml
You can try it yourself.
Login to the admin panel - standart.
I can give a link to FTP

**Comment by klocus** [comment]
Can you provide me this file: `/u14445mo3.ha002.t.justns.ru/public_html/tmp/sitemap.xml`?

**Comment by KonstantinFromRussia** [comment]
I can
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<?php $counter = 0; foreach (cv($urls) as $key => $value): ?>
<url>
    <loc><?php echo cv($value)['url']; ?></loc>
    <?php if (!empty($value['lastmod'])): ?><lastmod><?php echo cv($value)['lastmod']; ?></lastmod><?php endif; ?>

</url>
<?php $counter++; endforeach; ?>
</urlset>
```

**Comment by klocus** [comment]
Set the config option short_open_tag in php.ini to 0 or Off and restart Apache.

**Comment by KonstantinFromRussia** [comment]
Thanks!
It works. 
Will this parameter affect other sites on my server?

**Comment by KonstantinFromRussia** [comment]
A simpler solution to this problem.
Add the following code to the .htaccess file:

```
<IfModule mod_php5.c>
 php_flag short_open_tag off
</IfModule>
```

**Comment by vithultnair** [comment]
> A simpler solution to this problem.
> Add the following code to the .htaccess file:
> 
> ```
> <IfModule mod_php5.c>
>  php_flag short_open_tag off
> </IfModule>
> ```

This didn't fix my issue! `/sitemap.xml` gives a 500 error. 

`blog/feed/en_english` this also returns 500 error!

Is the issue fixed or not yet?
