### ISSUE TITLE
https://batflat.org pages return 404

### ISSUE THREAD

**Issue by sim2github** [sruupl/batflat#38]

**Comment by michu2k** [comment]
It looks like there no problem with the official website. 🤔

**Comment by sim2github** [comment]
I can access only to https://batflat.org/sitemap.xml
All other pages return `404 Not Found`

**Comment by sim2github** [comment]
Now works.

**Comment by sim2github** [comment]
Hmmm... Did not works till i not define language in URI. After this works fine. Seems the problem with definition lang from browser defaults, redirect to default language if not defined in cookies or smth like that. Will try to recreate issue.

**Comment by KonstantinFromRussia** [comment]
I observed a similar problem when entering from Russia.
Now everything is working.

**Comment by sim2github** [comment]
I cant reproduce on remote anymore. Will try locally with XDebug.

**Comment by joachim97** [comment]
Batflat ma kilka błędów których nie poprawili Twórcy w wersji 1.3.6.
Najważniejszym błędem jest to, że strona wyświetla się jako strona 404. Aby to naprawić wystarczy w pliku "batflat-master\inc\core\lib\Router.php" zmienić 64 linię ($url = trim(preg_replace('#'.$url.'#', '', $_SERVER['PATH_INFO'], 1), '/'); na $url = trim(str_replace($url, '',$_SERVER['PATH_INFO']), '/');. I błąd 404 znika.
