### ISSUE TITLE
Copyright bug ?

### ISSUE THREAD

**Issue by michu2k** [sruupl/batflat#4]
I don't know if it's a bug, but when you comment {$bat.powered}, it not showing up on page and we also don't see license system error.

**Comment by klocus** [comment]
@michu2k, po zakomentowaniu tej linii nie widać żadnego komunikatu o brakującej stopce? A sprawdź czy tryb deweloperski pokaże jakiś błąd ;)

**Comment by michu2k** [comment]
Testowałem na trybie deweloperskim i też nie wyskakuje żaden błąd.

**Comment by klocus** [comment]
Faktycznie, zakomentowany tag jest wykrywany jako poprawny.
