### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by sim2github** [sruupl/batflat#41]
What [about releases](https://help.github.com/articles/about-releases/)?
We can host [git archives](https://git-scm.com/docs/git-archive) on github by adding [tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging)  and relink to [latest release](https://help.github.com/articles/linking-to-releases/#linking-to-the-latest-release) on the [main site](https://batflat.org/download).

```
git tag v1.3.5
git push --tags
```

**Comment by klocus** [comment]
It's good idea.

**Comment by thomascenni** [comment]
This is a very good idea.
Using the official API to create a release:
https://developer.github.com/v3/repos/releases/#create-a-release
you'll get a downloadable zip or tar.gz file created automatically.
