### ISSUE TITLE
Multilang gallery module

### ISSUE THREAD

**Issue by sim2github** [sruupl/batflat#42]
Image description in gallery module must support multi lang as navigation and snippets modules does.

**Comment by klocus** [comment]
You can use Batflat's tags:

```
{lang: pl_polski}
    Witaj świecie!
{/lang}
{lang: en_english}
    Hello world!
{/lang}
```

:)

**Comment by sim2github** [comment]
You mean code to content form?
```
{lang: pl_polski}
    {$gallery.name1pl}
{/lang}
{lang: en_english}
    {$gallery.name1en}
{/lang}
```
In this case i duplicate images in upload

**Comment by klocus** [comment]
I mean use this in description field :)

**Comment by sim2github** [comment]
:) I get it. Need `info hint` in admin view.
Its not so obvious.
