### ISSUE TITLE
Can't Post US Currency In Pages / Posts -- Templates.php Tries To Process Them

### ISSUE THREAD

**Issue by volomike** [sruupl/batflat#44]
In your Templates.php file, in replaceVariable(), your Regular Expression is interpreting something like...

$9.99
$9.99/mo

...as some sort of variable like `$bat.path;` (and others) and is changing this to:

$9['99']
$9['99']/mo

You'll want to improve your Regular Expression to handle purely numerical conditions.

**Comment by michu2k** [comment]
Hey
I don't know if my answer will satisfy you, but you can disable parsing 
e.g.
`{noparse} 9.99 {/noparse}`
