### ISSUE TITLE
Routing reneval segment bug

### ISSUE THREAD

**Issue by RiddickAbaddon** [sruupl/batflat#49]
When I have Batflat in subfolder e.g domain.com/batflat i can't go into post list from tag named "batflat" in blog.

example:
domain.com/batflat/blog/tag/whatever            // work
domain.com/batflat/blog/tag/batflat                // error 404

It's about the name of the subfolder not the "batflat" name:

domain.com/cms/blog/tag/whatever            // work
domain.com/cms/blog/tag/cms                    // error 404

The error occurs in freshly installed cms

In debug mode last query is: SELECT * FROM pages WHERE slug LIKE ? AND lang = ?
as if  i was asking about a non-existent nested subpage like: domain.com/page/notexist. No blog module query.

**Comment by michu2k** [comment]
Hi
It's a known issue. I will take a look at this.
