### ISSUE TITLE
Sort posts by tags

### ISSUE THREAD

**Issue by senwmn** [sruupl/batflat#56]
Hi, love the CMS!

I'm still a beginner with backend development and am struggling to grasp how posts populate. I want to only display posts with specific tags on specific pages and add extra post fields which can be displayed in my markup.
The end goal of my project is to have editable content for upcoming local events, so on my page I currently have a 2 column grid layout which i want to display each post in, howver i still ned to add more 'fields'. Some examples would be adding a date and location wyswig field to each post.

Heres my code (I've added different variable names to represent the new fields - you get the picture):

**{template: inc/header.html}
<div id="header1a" class="fullimg"></div>

<div class="fullimg none">
</div>

 <main class="container">

        <div class="logo-mobile"></div>

        {template: inc/sidebar.html}

        <div class="content">
                <h1>{$page.title}</h1>
           
            <div class="content-area" id="dining">

                    {loop: $blog.posts}

                    <article class="content-box">
                            {if: $value.cover_photo}
                            <img src="{$value.cover_url}" class="featuring-image" />
                            {/if}
                            <div class="inner-content">
                              <span class="title">{$event.title}</span><br>
                              <span class="location">{$location.content}</span>
                              <p class="booking-details">
                                  <span class="action">Book now</span> <br>
                                  <a href="https://askitalian.co.uk/christmas">www.askitalian.co.uk/christmas</a> <br>
                                  <span>{$contactnumber.content}</span>
                              </p>
                              {$value.content}
                          </div>
                      </article>
                {/loop}
            </div>
               
{template: inc/footer.html}
                </div>
                    </main>

{template: inc/nav.html}
{template: inc/scripts.html}**

Ive also tried adding to the site.php page but i'm not sure how to go about this. Sorry if its a bad question, didn't want to use wordpress and this was the best lightweight alternative i've found!

**Comment by michu2k** [comment]
Hello
Thanks for choosing Batflat for your website! 
As for tags, there is already a question and answer about this feature [here](https://github.com/sruupl/batflat/issues/27#issuecomment-415387505) and [here](https://github.com/sruupl/batflat/issues/27#issuecomment-415544915). Sadly in Polish, but you have the code and how it works. You need to edit `_getLatestPosts()` function (or create a new one). When it comes to additional 2 fields, unfortunately, I can't answer that question for you, because I need to reproduce it first, but don't have too much time now.

**Comment by senwmn** [comment]
Hey, thanks so much for the fast reply and linking the other features, I'll give them a try!

**Comment by michu2k** [comment]
The problem seems to be resolved. If you have further questions or problems, please create a new issue.

**Comment by michu2k** [comment]
The problem seems to be resolved. If you have further questions or problems, please create a new issue.
