### ISSUE TITLE
Admin panel does not work?

### ISSUE THREAD

**Issue by bkauler** [sruupl/batflat#6]
I have just installed version 1.3.3, went to my website, admin folder, logged in with "admin" username and password, then got a page as shown. 

There are no tabs. Nothing. Is this a bug? Have I done something wrong?

Note, I have a shared account, host is omnis.com

Snapshot of admin window:

[http://barryk.org/easy/batflat-admin.png](http://barryk.org/easy/batflat-admin.png)

Regards,
Barry

**Comment by sruupl** [comment]
Hi,

Turn on the dev mode in inc/core/defines.php and see if you get any error.

**Comment by bkauler** [comment]
Hi,
OK, turned on dev mode.

In the black side panel, get this:

------------
Notice: Undefined index: nav in
/webroot/b/k/bkauler001/bkhome.org/www/batflat/admin/tmp/index.html on
line 35

Warning: Invalid argument supplied for foreach() in
/webroot/b/k/bkauler001/bkhome.org/www/batflat/admin/tmp/index.html on
line 35
-------------

In the main white part of the window, get this:

----------------------
Notice: Undefined variable: module in
/webroot/b/k/bkauler001/bkhome.org/www/batflat/admin/tmp/index.html on
line 81

Notice: Undefined variable: module in
/webroot/b/k/bkauler001/bkhome.org/www/batflat/admin/tmp/index.html on
line 82
-----------------------

Regards,
Barry Kauler

**Comment by klocus** [comment]
Try install Batflat on another host, then copy inc/data/database.sdb to your website. I think some data is not properly installed.
