### ISSUE TITLE
Snippets editor overwrites languages if html is edited directly

### ISSUE THREAD

**Issue by juliuszfedyk** [sruupl/batflat#7]
Hi, I have an issue with the snippets module. When I edit the snippet in the code view - once saved, the last edited code is saved in all languages.
- create snippet
- put some text in each language version in normal editor
- go to language 1
- click on code editor
- insert i.e.:
```
<header class="align-center">
  <p>visit our venue</p>
  <h2><a href="" class="button">Book now!</a></h2>
</header>
```
- click save

what should happen:
- only version for language 1 should resemble the code

what happens:
- all version are overwritten with the edited code

So far tried only on my dev host.

**Comment by klocus** [comment]
It is summernote (WYSIWYG) bug. You have to disable "Code View" before saving.
