### ISSUE TITLE
 BatFlat-FilesToDownload 

### ISSUE THREAD

**Issue by sherzog01** [sruupl/batflat#71]
Hi,
I found the module on GitHub and it is very useful. Is there a way to rewrite the script that it checks before uploading is the file or slug already exists in the database?

The problem is if you upload twice time a file with the same name, you can no longer delete it or it can only be deleted once, the other entry is retained but without the file.

Thx and regrads.

**Comment by michu2k** [comment]
Hi
This is a module created by the community.
You should ask this question in the module repository or write to the author
➡️  https://github.com/piotr-placzek/BatFlat-FilesToDownload/issues

**Comment by sherzog01** [comment]
OK thx for the fast anwser. I will try to connect the author. 

Thank you and great job!
