### ISSUE TITLE
Change Editor in Batflat CMS, and more Addons

### ISSUE THREAD

**Issue by ArmendHajdari** [sruupl/batflat#72]
Change Editor in Batflat CMS, 

Maybe you should bring something better about this part.

Maybe, https://imperavi.com/redactor/ , https://froala.com/wysiwyg-editor/ 

Will we have any innovations from the Addons, Themes, Plugins section.

Suggestions:
A general manual is needed that explains each plugin how to use, what should be used in the template, etc ... ( Sample: https://www.pulsecms.com/help/convert-html-template-to-pulse )

For the good of Batflat,
All the best,
Armendi :)

**Comment by sujaysreedhar** [comment]
+1 for froala

**Comment by michu2k** [comment]
Hello
1. Batflat currently uses [summernote](https://summernote.org/) WYSIWYG editor
2. I don't think there will be more addons in this Batflat version

**Comment by Every0ne** [comment]
>     2\. I don't think there will be more addons in this Batflat version

@michu2k, you've already made a few statements about feature freeze on version 1.3. Do you have, or can point to any information regarding the next version?

**Comment by michu2k** [comment]
Hi @Every0ne 
Unfortunately, I don't know when the next update will happen, but there will definitely be new things.
