### ISSUE TITLE
Custom field as css class for posts

### ISSUE THREAD

**Issue by lowpez** [sruupl/batflat#74]
Hello batflat Team!
I would like to include a special css class for each post. Can I add / set up this type of feature as a text input field? If is a "yes" how?
Thanks!

**Comment by michu2k** [comment]
Hi @lowpez 
Steps you need to do:
1. Add input to your view `view/admin/form.html`
2. Add lang strings `lang/admin`
3. Add field to DB `Info.php` (`blog` table)
4. Add field to `Admin.php`. I think you only need to edit the `getEdit` function.
5. Add your variable to `YOUR_THEME/post.html` and/or to `YOUR_THEME/blog.html`

There is nothing to do in `Site.php`, it should work without any modifications but I'm not 100% sure.
There are only general steps that you need to know. If you know the basics of PHP, then you should handle this. All you need to do is: 
- Add view,
- Add field to DB,
- Add field to the appropriate functions in PHP

**Comment by w3bd3mon** [comment]
Hello Michael,

I have reported a few bugs to you via my other email 3 days back from
Vinit.patil2790@gmail.com.
Request you to kindly revert on the same.

Thanks and Regards,
Vinit Patil

**Comment by michu2k** [comment]
Hi @w3bd3mon 
Sorry but I didn't receive an email from you. Can you send me an email again? michal.strumpf@gmail.com

Regards

**Comment by lowpez** [comment]
@michu2k ,
Thanks! Well i was wondering about blog post. Let's hope i can :P

**Comment by michu2k** [comment]
I am not sure if I understood but this code below will check if the post has the `featured` tag.

```html
{loop: $value.tags as $tag}
    {if: $tag.slug == 'featured'}
        <span class="featured">{$tag.name}</span>
    {/if}
{/loop}
```

**Comment by w3bd3mon** [comment]
Hello Michael,

I have sent an email on the official batflat email id's. Can you please let
me know  whether I should raise an issue via github or else which of the
official email addresses.

**Comment by michu2k** [comment]
@w3bd3mon 
Ah, ok. I don't have access to the official Bf email address, so I can't reply to your email.
@klocus can answer :)

**Comment by lowpez** [comment]
@michu2k ,
Thanks mate! 🤘🐶🎸
