### ISSUE TITLE
Issues with https

### ISSUE THREAD

**Issue by vithultnair** [sruupl/batflat#76]
Hi batflat Community,

Cover/featured image url, tags input in admin panel and og meta properties doesn't seems to work properly while using ssl.
 * Cover/featured image and some og meta properties( especially og:image ) seems to be using http link even after enabling https.
 * In the admin panel the tag input doesn't show tags as we type in https, but it is working fine without ssl.

Suggestions:
An option to add cover/featured image from an external link so that one can add image from cdns like cloudinary! It would be helpful for those who is on a shared hosting with limited resources.

**Comment by michu2k** [comment]
Hi
Please, check if you don't have hard-coded `http` instead of `https` in your theme.

**Comment by vithultnair** [comment]
Not really! I checked everything and found the http links are generated by the following elements 
   `{$value.cover_url}` - (In blog file)
   `{$post.cover_url}` - (In post file)
   `{?= $post.author.avatar ?}` - (In post file)
All of these are dynamically generated and have nothing to do with the theme!

I've made a temporary fix by using str replace, but i know it's not a right thing to do.
`<img src="{?= str_replace( 'http://', 'https://', $value.cover_url ) ?}" alt="{$value.title}">`

Also the og:image attribute being generated automatically is having an http url, but i couldn't figure out where it is being generated from! :(

**Comment by vithultnair** [comment]
Not really! I checked everything and found the http links are generated by the following elements 
   `{$value.cover_url}` - (In blog file)
   `{$post.cover_url}` - (In post file)
   `{?= $post.author.avatar ?}` - (In post file)
All of these are dynamically generated and have nothing to do with the theme!

I've made a temporary fix by using str replace, but i know it's not a right thing to do.
`<img src="{?= str_replace( 'http://', 'https://', $value.cover_url ) ?}" alt="{$value.title}">`

Also the og:image attribute being generated automatically is having an http url, but i couldn't figure out where it is being generated from! :(

**Comment by michu2k** [comment]
Batflat has https support and should generate the URL correctly. Maybe you can try to force your website to redirect to https. 
https://stackoverflow.com/questions/4398951/force-ssl-https-using-htaccess-and-mod-rewrite

**Comment by vithultnair** [comment]
That didn't make a change! Still the urls generated are `http://` ! It would be better if there was an option to enter the base url in admin panel which will prevent issues like this!

**Comment by michu2k** [comment]
Enable **DEV_MODE** in `inc/core/defines.php`
Open DebugBar and in **Requests** tab should be` [HTTPS] => on`. If you can't find this line, then there is probably a problem with your server. Please check if our SSL is correctly installed.

If the problem persists, you can manually set the https protocol:
Open `inc/core/lib/functions.php`;
Find `$protocol = 'http://';` and replace with `https://`.

Cheers

**Comment by vithultnair** [comment]
Got it working finally! I didn't have an SSL at my origin server, i was using cloudflare SSL. So the script couldn't determine that my site have an SSL! eventhough this is not a permanent fix ,this will solve my problem for now! Thanks @michu2k 

Btw please not that Batflat couldn't determine whether the site is on https or not correctly while the site uses an ssl from cdn like cloudflare.

Also please lemme know if there is any fix for error with Sitemap module(error code: 500) .

**Comment by michu2k** [comment]
There is no official fix for the sitemap error.
You can check possible fixes created by sim2github https://github.com/sruupl/batflat/pull/39

**Comment by vithultnair** [comment]
Thanks again @michu2k 
Loving Batflat

**Comment by renatofrota** [comment]
> Not really! I checked everything and found the http links are generated by the following elements
> `{$value.cover_url}` - (In blog file)
> `{$post.cover_url}` - (In post file)
> `{?= $post.author.avatar ?}` - (In post file)
> All of these are dynamically generated and have nothing to do with the theme!
> 
> I've made a temporary fix by using str replace, but i know it's not the right thing to do.
> `<img src="{?= str_replace( 'http://', 'https://', $value.cover_url ) ?}" alt="{$value.title}">`
> 
> Also the og:image attribute being generated automatically is having an http url, but i couldn't figure out where it is being generated from! :(

#79 fixes the problem. Merged to master already, should be released next update or you can add the line manually: https://github.com/sruupl/batflat/pull/79/commits/b054bd67e954dca6a8a1176084eb369a3dff33c3
