### ISSUE TITLE
No text in Admin Menu

### ISSUE THREAD

**Issue by leookny** [sruupl/batflat#78]
Hey, I just installed the version and I have no labels or text in the admin menu. So I enabled dev mode and this is what I got 

Warning: parse_ini_file() has been disabled for security reasons in /var/webs/www.tinails.ch/public_html/inc/core/Admin.php on line 89

Warning: parse_ini_file() has been disabled for security reasons in /var/webs/www.tinails.ch/public_html/inc/core/Admin.php on line 89

Warning: array_merge(): Argument #1 is not an array in /var/webs/www.tinails.ch/public_html/inc/core/Admin.php on line 89

Line 89 seems to be related to the language files. How can I fix it ? Thank you so much

**Comment by michu2k** [comment]
Hi @leookny 
This means your hosting company or server administrator has disabled `parse_ini_file()` function. You should write to your hosting company how to enable this function.
