### ISSUE TITLE
Page with a slug of "/" causes a bug

### ISSUE THREAD

**Issue by nzjs** [sruupl/batflat#82]
Hi, when adding a new page and setting the slug as "/", it causes an issue with Settings > General > Homepage, and prevents this setting from being saved.

I realise now that if you want a page to be the home page (and appear as / ) then you still need to add a slug, and Batflat takes care of the rest nicely. 

Perhaps prevent the user from setting "/" as the slug. When I entered this and saved the page, it blanks the slug but still seems to work.

**Comment by michu2k** [comment]
Thanks for the report

**Comment by michu2k** [comment]
Fixed
