### ISSUE TITLE
License System

### ISSUE THREAD

**Issue by smitti** [sruupl/batflat#88]
After editing the header-images from theme "Blue" and flashing the cache after that I got the message: 
`Batflat` license system
The return link has been deleted or modified.``
I haven´t changed anything there. The only theme now running is the theme "Blue".

**Comment by michu2k** [comment]
Hello @smitti 
I tried to reproduce your problem but I didn't find any bug with that. Try to upload the theme again.

**Comment by smitti** [comment]
Hello @michu2k 
okay, thank you. I´ll try it.

**Comment by smitti** [comment]
Solved. Thank you.
