### ISSUE TITLE
License

### ISSUE THREAD

**Issue by smitti** [sruupl/batflat#95]
Impossible to get a license?

**Comment by michu2k** [comment]
I believe that you don't need a license for the current version of Batflat.

**Comment by smitti** [comment]
Unfortunately no, with my installation the site stopped working after removing the {$ bat.powered} tag. Greetings Uwe

**Comment by klocus** [comment]
@smitti Just add HTML comment tag into`{$bat.powered}`:)

```html
<!-- {$bat.powered} -->
```

**Comment by smitti** [comment]
@klocus yes, I know. But I don´t want to use the tag.
