### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by smitti** [sruupl/batflat#96]
Does anybody know anything about the future of batflat cms?

**Comment by michu2k** [comment]
Hi @smitti 
As far as I know, work on a new version of cms is in progress, but unfortunately I don't know any more details.

**Comment by smitti** [comment]
That's good news. Thank you.

**Comment by klocus** [comment]
Development of the current version is stopped. Work will only continue on a completely new version.
Zapisz tłumaczenie

**Comment by smitti** [comment]
…how can I get a license for the current version?

**Comment by klocus** [comment]
You can't. Sorry for that.
