### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by piotr-placzek** [sruupl/batflat#97]
The current license prevents the creation of a website for the client using BatFlat. Many of my clients are interested in your system because of its simplicity.

Unfortunately, payment via https://batflat.org/buy is blocked.

http://feed.sruu.pl/batflat/commercial/payment/paypal returns the answer:
`Got Http response code 400 when accessing https://api.paypal.com/v1/oauth2/token.` 

The https://sruu.pl website looks closed.

You do not respond to e-mails sent from the https://batflat.org/pl/contact form.

You do not respond to e-mails sent directly to the address kontakt@sruu.pl.

**SO, how we can create BF based websites for our clients?**
Have you thought about updating the license terms? Maybe the MIT license?

**Comment by klocus** [comment]
Hi,

You can use free license for clients. I will update the current license on Batflat's website. You can even remove footer without license.

**Comment by klocus** [comment]
Licencja wersji darmowej została poprawiona (zarówno na stronie jak i w repo). W najbliższym czasie usunę również sprawdzanie wersji komercyjnej z plików BF.

**Comment by piotr-placzek** [comment]
Dzięki. Backlink to już nie taki problem, przeważnie klienci nie mają nic
przeciwko.

pon., 11 sty 2021, 12:38 użytkownik Paweł Klockiewicz <
notifications@github.com> napisał:
