### ISSUE TITLE
Code injection vulnerability in Batflat v1.3.6 Users tab

### ISSUE THREAD

**Issue by mari0x00** [sruupl/batflat#98]
Users tab attributes aren't sanitized and some of them allow for code injection. This means that an authenticated user with access to Users tab can execute arbitrary code on the web server with application privileges. 

Adding user with PHP code in "Displayed name" field:

![image](https://user-images.githubusercontent.com/25896006/105181948-bba87480-5b2c-11eb-9f53-9a82e4ca01fd.png)

PHP being executed:

![image](https://user-images.githubusercontent.com/25896006/105182216-1346e000-5b2d-11eb-9c57-1c9e752990d7.png)

**Comment by theofruitrouge** [comment]
This should be fixed ASAP.

**Comment by michu2k** [comment]
Fixed. The fix will be available in the next update.
